services:
  - type: web
    name: my-aspnet-app
    runtime: dotnet
    repo: https://github.com/ChikawaS04/bank-project
    branch: main
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/BankApp.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
